
/* Created by : Sindhu Pathipati
      On date : July 2026  */

/*1.What is the total sales revenue generated by the company*/
 
SELECT 
ROUND(SUM(Sales), 2) AS Total_Sales
FROM superstore;

/* 2.What is the total profit?*/

SELECT 
ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore;

/*3. Which product categories generate the highest sales?*/

SELECT Category,
       ROUND(SUM(Sales), 2) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;

/*4.Which sub-categories generate the highest sales?*/

SELECT "Sub-Category",
       ROUND(SUM(Sales),2) AS  Total_Sales
FROM superstore
GROUP BY "Sub-Category"
ORDER BY Total_Sales DESC;

/*5.Which regions generate the highest sales? */

SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;

/*6. Who are the top 10 customers by sales?*/
Select "Customer Name",
ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;

/*7. Which products are generating losses for the company?*/

SELECT "Product Name",
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY "Product Name"
HAVING Total_Profit < 0
ORDER BY Total_Profit ASC
LIMIT 10;

/*8. Which customer segment contributes the highest revenue? */

SELECT Segment,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Segment
ORDER BY Total_Sales DESC;

/*9. Which states generate the highest sales?*/

SELECT State,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;

/*10. Which products generate the highest profit?*/

SELECT "Product Name",
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 10;

/*11. Which states generate the highest profit? */
 SELECT State,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 10;

/* 12. What is the average sales amount for each customer segment?*/
SELECT Segment,
       ROUND(AVG(Sales),2) AS Average_Sales
FROM superstore
GROUP BY Segment
ORDER BY Average_Sales DESC;

/* 13. Which are the top 10 products sold in the highest quantities?*/

SELECT "Product Name",
       SUM(Quantity) AS Total_Quantity
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Quantity DESC
LIMIT 10;

